steps:
  - id: Build
    name: 'gcr.io/cloud-builders/docker'
    env:
      - 'PORT=3000'
    args:
      - 'build'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world:$SHORT_SHA'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world:latest'
      - '.'

  - id: Generate manifest
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
        sed "s/COMMIT_SHA/${SHORT_SHA}/g" > kubernetes.yaml

  - id: Deploy
    name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cloudbuild'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes.yaml'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world'
