steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$_DOCKER_USERNAME --password=$_DOCKER_PASSWORD', '&&', 'docker build -t asia-docker.pkg.dev/docker-nodejs-hello-world .']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    entrypoint: 'bash'
    waitFor: ['docker-build']
    args: ['-c', 'docker login --username=$_DOCKER_USERNAME --password=$_DOCKER_PASSWORD', '&&', 'docker push asia-docker.pkg.dev/docker-nodejs-hello-world']

options:
  logging: CLOUD_LOGGING_ONLY

images: ['asia-docker.pkg.dev/docker-nodejs-hello-world']
