steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world .']

options:
  logging: CLOUD_LOGGING_ONLY

images: ['asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world']
