steps:
  - name: node
    entrypoint: npm
    args: ["install"]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker login --username=$_DOCKER_USERNAME --password=$_DOCKER_PASSWORD'
      - '&&'
      - 'docker build .'

options:
  logging: CLOUD_LOGGING_ONLY
