steps:
  - name: node
    entrypoint: npm
    args: ["install"]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker login --username=$_DOCKER_USERNAME --password=$_DOCKER_PASSWORD'
      - '&&'
      - 'docker build .'

images:
  - 'gcr.io/docker-nodejs-hello-world:${SHORT_SHA}'
  - 'gcr.io/docker-nodejs-hello-world:latest'

options:
  logging: CLOUD_LOGGING_ONLY
