steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'BUILD'
    args:
      - 'build'
      - '-t asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world:$SHORT_SHA'
      - '-t asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world:latest'
      - '.'
    env:
      - 'PORT=80'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia.gcr.io/$PROJECT_ID/docker-nodejs-hello-world'
