steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'BUILD'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/docker-nodejs-hello-world', '.']

options:
  logging: CLOUD_LOGGING_ONLY

images: ['asia-southeast1-docker.pkg.dev/$PROJECT_ID/docker-nodejs-hello-world']
