steps:
  - name: node
    entrypoint: npm
    args: ["install"]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker login --username=$_DOCKER_USERNAME --password=$_DOCKER_PASSWORD'
      - '&&'
      - 'docker build -t gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA} .'

images:
  - 'gcr.io/${PROJECT_ID}/${REPO_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
