steps:
  - name: node
    entrypoint: npm
    args: ["install"]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
    args: ['-c', 'docker login --username=$$DOCKER_USERNAME --password=$$DOCKER_PASSWORD']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}', '.']

  - name: hashicorp/terraform
    entrypoint: sh
    secretEnv:
      - 'HELLO'
    args:
      - '-c'
      - |
        echo "HELLO" $$HELLO

availableSecrets:
  secretManager:
    - versionName: projects/708036783844/secrets/HELLO/versions/latest
      env: 'HELLO'
    - versionName: projects/708036783844/secrets/DOCKER_USERNAME
      env: 'DOCKER_USERNAME'
    - versionName: projects/708036783844/secrets/DOCKER_PASSWORD
      env: 'DOCKER_PASSWORD'

images:
  - 'gcr.io/${PROJECT_ID}/${REPO_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
